version: '3.8'

services:
  mongodb:
    container_name: mongodb-service-container
    image: mongo:7
    restart: unless-stopped
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-root}
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  redis:
    container_name: redis-service-container
    image: redis:7
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    networks:
      - backend

  redis-commander:
    container_name: redis-commander-container
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - '8088:8081'
    depends_on:
      - redis
    networks:
      - backend

volumes:
  mongodb_data:
  redis_data:

networks:
  backend:
    driver: bridge